export { ProfilesPage } from './ProfilesPage';
export { VersionsPage } from './VersionsPage';
export { InstancesPage } from './InstancesPage';
export { SettingsPage } from './SettingsPage';
export { WizardPage } from './WizardPage';
export { JavaPage } from './JavaPage';
export { NodePage } from './NodePage';
export { MavenPage } from './MavenPage';
export { LicensesPage } from './LicensesPage';
